version: '3'
services:
  db:
    image: mariadb:10.10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MARIADB_DATABASE: doit
      MARIADB_ROOT_PASSWORD: knjo41dsS!
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql
    ports:
      - "12450:3306"

  redis:
    restart: always
    image: redis:7-bullseye
    ports:
      - '12451:6380'
    command: redis-server --port 6380
    volumes:
      - ./docker/redis:/data'