#!/bin/zsh

### please do NOT run this script directly
### this file should be run by yarn init-app in root workspace

ANSI_RED='\x1b[31m'
ANSI_GREEN='\x1b[32m'
ANSI_RESET='\x1b[0m'

SHARED_PATH='./packages/shared'
SERVER_PATH='./packages/server'
WEB_PATH='./packages/solid_web'
ELECTRON_PATH='./packages/electron_app'

create_dotenv() {
  if [ $# -ne 1 ]; then
    echo "${ANSI_RED}create dotenv argument incorrect.${ANSI_RESET}"
    return 1
  fi

  echo '# do NOT edit this file.' >"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  echo '# This file is created automatically by run yarn init-app.' >>"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  echo "DOIT_ROOT=$(pwd)" >>"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  return 0
}

create_dotenv $SHARED_PATH
create_dotenv $SERVER_PATH
create_dotenv $WEB_PATH
create_dotenv $ELECTRON_PATH

echo "${ANSI_GREEN}init app successful.${ANSI_RESET}"
