#!/bin/zsh

### please do NOT run this script directly
### this file should be run by yarn init-app in root workspace

ANSI_RED='\x1b[31m'
ANSI_GREEN='\x1b[32m'
ANSI_YELLOW='\x1b[33m'
ANSI_BLUE='\x1b[34m'
ANSI_RESET='\x1b[0m'

SHARED_PATH='./packages/shared'
SERVER_PATH='./packages/server'
WEB_PATH='./packages/solid_web'
ELECTRON_PATH='./packages/electron_app'

create_dotenv() {
  if [ $# -ne 1 ]; then
    echo "${ANSI_RED}create dotenv argument incorrect.${ANSI_RESET}"
    return 1
  fi

  echo '# do NOT edit this file.' >"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  echo '# This file is created automatically by run yarn init-app.' >>"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  echo "DOIT_ROOT=$(pwd)" >>"$1/.env.local"
  if [ $? -ne 0 ]; then
    return 1
  fi

  return 0
}

main() {
  echo "${ANSI_BLUE}INFO${ANSI_RESET} init start..."

  create_dotenv $SHARED_PATH
  create_dotenv $SERVER_PATH
  create_dotenv $WEB_PATH
  create_dotenv $ELECTRON_PATH

  echo "DATABASE_URL=$PRISMA_DB_URL" >>"$SERVER_PATH/.env.local"

  # make logs directory
  mkdir logs

  echo "${ANSI_GREEN}DONE${ANSI_RESET} init app successful."
}

echo "${ANSI_BLUE}INFO${ANSI_RESET} please input prisma database url:"
PRISMA_DB_URL=
vared PRISMA_DB_URL
echo "your db url is: (${PRISMA_DB_URL}), is OK? [y/n]: "
while read "PRISMA_OK"; do
  case $PRISMA_OK in
  [Yy]) {
    main
    exit 0
  } ;;
  [Nn]) {
    echo "${ANSI_YELLOW}WARN${ANSI_RESET} you say no, please check the database url and start again."
    exit 1
  } ;;
  *) {
    echo "please answer with Yy or Nn"
  } ;;
  esac
done
